services:
  microcart-app: # Name of the service
    container_name: microcartv2
    build: # Explains where the DockerFile can be found
      context: .
      dockerfile: ./docker/dev/DockerFile
    ports: # Opens the ports up
      - "3000:3000"
    restart: always # Restarts the container if it crashes
    volumes: # Maps the local directory to the container
      - .:/app
      - /app/node_modules
    env_file: # Loads the environment variables
      - development.env
    depends_on:
      - microcart-postgres # Depends on the postgresql service

  # This sets up the postgres service for the app
  microcart-postgres:
    image: postgresql:16-alpine3.19
    ports: 
      - 5432:5432
    restart: always
    volumes: # where the data is stored
      - postgresql-data:/var/lib/postgresql/data
    environment: # Sets the environment variables for the postgres service (username, password, db)
      - POSTGRES_USER=s(DB_USER)
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=microcart

volumes:
  microcart-postgres:

# docker compose build --pull --no-cache