services:
  microcart-app:
    container_name: microcart-app
    build: 
      context: .
      dockerfile: ./docker/development/Dockerfile
    ports:
      - 3000:3000
    restart: always
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - microcart-postgres

  microcart-postgres:
    image: postgres:16-alpine3.19
    ports:
      - 5432:5432
    restart: always
    volumes:
      - microcart-postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=db_test

volumes:
  microcart-postgres:
  