CREATE TABLE IF NOT EXISTS "role" (
  id SERIAL PRIMARY KEY,
  name VARCHAR(45) DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS "admin" (
  id SERIAL PRIMARY KEY,
  username VARCHAR(45) DEFAULT NULL,
  password VARCHAR(45) DEFAULT NULL,
  created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  role_id INT REFERENCES "role" (id) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT unique_username UNIQUE (username)
);

CREATE TABLE IF NOT EXISTS "shop" (
  id SERIAL PRIMARY KEY,
  admin_id INT REFERENCES "admin" (id) ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE TABLE IF NOT EXISTS "theme" (
  id SERIAL PRIMARY KEY,
  name VARCHAR(45) DEFAULT NOT NULL
  source VARCHAR(45) DEFAULT NOT NULL 
);

CREATE TABLE IF NOT EXISTS 'user' (
  cart_id JSONB NOT NULL DEFAULT '{}',  -- Use JSONB data type for Postgres
  id SERIAL PRIMARY KEY,
  username VARCHAR(45) DEFAULT NULL,
  password TEXT DEFAULT NULL,  -- Use TEXT data type for Postgres
  name VARCHAR(45) DEFAULT NULL,
  shipping_id INT REFERENCES 'shipping' (id) ON DELETE NO ACTION ON UPDATE NO ACTION,
  email VARCHAR(45) DEFAULT NULL,
  billing_id INT REFERENCES 'shipping' (id) ON DELETE NO ACTION ON UPDATE NO ACTION,
  created TIMESTAMP DEFAULT NULL,
  role_id INT REFERENCES 'role' (id) ON DELETE NO ACTION ON UPDATE NO ACTION,
  theme_id INT REFERENCES 'theme' (id) ON DELETE NO ACTION ON UPDATE NO ACTION
);





CREATE TABLE IF NOT EXISTS template.category (
  id SERIAL PRIMARY KEY,
  name VARCHAR(45) DEFAULT NULL,
  parent_id INT NOT NULL
);


CREATE TABLE IF NOT EXISTS template.order (
  id SERIAL PRIMARY KEY,
  user_id INT NOT NULL REFERENCES dev.user (id) ON DELETE NO ACTION ON UPDATE NO ACTION,
  created TIMESTAMP DEFAULT NULL,
  shipping_id INT REFERENCES dev.user (shipping_id) ON DELETE NO ACTION ON UPDATE NO ACTION,
  status INT DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS template.product (
  shop_id SERIAL NOT NULL,
  id SERIAL PRIMARY KEY,
  name VARCHAR(45) DEFAULT NULL,
  price DECIMAL(10,2) DEFAULT NULL,
  image VARCHAR(45) DEFAULT NULL,
  size VARCHAR(10) DEFAULT NULL,
  details TEXT DEFAULT NULL,
  category_id INT NOT NULL REFERENCES template.category (id) ON DELETE NO ACTION ON UPDATE NO ACTION,
  keywords TEXT DEFAULT NULL,
  sku VARCHAR(10) DEFAULT NULL,
  created TIMESTAMP DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS template.order_product (
  id SERIAL PRIMARY KEY,
  order_id INT REFERENCES template.order (id) ON DELETE NO ACTION ON UPDATE NO ACTION,
  product_id INT REFERENCES template.product (id) ON DELETE NO ACTION ON UPDATE NO ACTION,
  quantity INT DEFAULT NULL
);